name: Push latest Docker image
on:
  push:
    branches:
      - main
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build --tag mactavishediting/latex:latest --tag mactavishediting/latex:${GITHUB_SHA:0:4} .
    - name: Clone template
      run: git clone https://github.com/mactavishediting/paper.tex.git
    - name: Verify we can build the PDF
      run: docker run --name latex --volume ${PWD}/paper.tex/paper.tex:/workdir/paper.tex mactavishediting/latex:latest make
    - name: Copy the PDF
      run: docker cp latex:/workdir/paper.pdf $PWD
    - name: Save the PDF
      uses: actions/upload-artifact@v3
      with:
        name: paper
        path: paper.pdf
    - name: Docker log-in
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - name: Push latest Docker image
      run: docker push mactavishediting/latex:latest
    - name: Push sha Docker image
      run: docker push mactavishediting/latex:${GITHUB_SHA:0:4}
